# Generated by Django 5.0.2 on 2024-06-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('name', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
            ],
            options={
                'verbose_name': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['name'],
                'index_together': {('name', 'category')},
            },
        ),
    ]
